jobs:
  include:
    - language: node_js
      node_js: 12
      cache:
        directories:
          - node_modules
      addons:
        sonarcloud:
          organization: "the-sciences-and-engineering-squad" # the key of the org you chose at step #3
          token:
            secure: "E03doSSvQcZEbLh01vU5BMDtxdavwhKo8OnwueZgsQNfgX9tZOcaEBB9F7fZre7SoSqwx0C8XmEX2Rlf2ERD97gBQSjWT6Nh4f3dKVCIjqlR/AD8i1OoiIpbs6ihtmwxIN2PRzKcUc3JSnt2uT54YeCWAYaQWWRmggRXYVQ3HDWj+fhNNMDvLp0ty36f6C+gX1D5qUvq3yJ0uzDZsMo/heTOU2vi0x8Fmwgup6B75lnhhDD0mHmf4KUiPvnhdmcOaWH0jriTAC69fHYYcn4y1u/UPXbBqSUDRJnzFSjlxEvmiM9dO2KcbYokFxTQtktsTJmH4x/kmYbUC8C+YJ7rDhssO82ax2OqoJZ92fbg3NbvqH1xmLDJ1SxfJ9cu/mg07daO2bE8peETPTiIx7BastVvw/oq8rr+7+SqIyKyRBlz7kzBcw3FZsjoTeN22bd7tSdSxnS2qbxuKIwsMxaCg+lC27y39IKeCoeYwWDyRIa7EbUBSEJAOWg/RqCkqM0cwHFTChzuO9XgU3X8VbgryCtBjN33r0MfoxXbNUm5NpExL/VikUEj/zJ0KukhI4ELmcpKLadJGDyCL5y69MPxFuRDz3i0K6TjoFojyi/Lt2Pipwly9OI19Xu0s2wBEOSM9UqQlOpyWy5sPYQY2CYlhmNCV7zSJfKd9fmN5P18QNE="      before_install:

      before_install:
        - cd client
      install:
        - npm install
      script:
        - npm test
        - npm run test:coverage
        - npm run build
        # other script steps might be done before running the actual analysis
        - sonar-scanner
    - language: python
      env:
        - FLASK_APP=server
        - FLASK_ENV=development
      addons:
        sonarcloud:
          organization: "the-sciences-and-engineering-squad" # the key of the org you chose at step #3
          token:
            secure: "E03doSSvQcZEbLh01vU5BMDtxdavwhKo8OnwueZgsQNfgX9tZOcaEBB9F7fZre7SoSqwx0C8XmEX2Rlf2ERD97gBQSjWT6Nh4f3dKVCIjqlR/AD8i1OoiIpbs6ihtmwxIN2PRzKcUc3JSnt2uT54YeCWAYaQWWRmggRXYVQ3HDWj+fhNNMDvLp0ty36f6C+gX1D5qUvq3yJ0uzDZsMo/heTOU2vi0x8Fmwgup6B75lnhhDD0mHmf4KUiPvnhdmcOaWH0jriTAC69fHYYcn4y1u/UPXbBqSUDRJnzFSjlxEvmiM9dO2KcbYokFxTQtktsTJmH4x/kmYbUC8C+YJ7rDhssO82ax2OqoJZ92fbg3NbvqH1xmLDJ1SxfJ9cu/mg07daO2bE8peETPTiIx7BastVvw/oq8rr+7+SqIyKyRBlz7kzBcw3FZsjoTeN22bd7tSdSxnS2qbxuKIwsMxaCg+lC27y39IKeCoeYwWDyRIa7EbUBSEJAOWg/RqCkqM0cwHFTChzuO9XgU3X8VbgryCtBjN33r0MfoxXbNUm5NpExL/VikUEj/zJ0KukhI4ELmcpKLadJGDyCL5y69MPxFuRDz3i0K6TjoFojyi/Lt2Pipwly9OI19Xu0s2wBEOSM9UqQlOpyWy5sPYQY2CYlhmNCV7zSJfKd9fmN5P18QNE="      before_install:
      before install:
        - cd server
      install:
        - pip install -r requirements.txt
      script:
        - python3 __init__.py
        - sonar-scanner