jobs:
  include:
    - language: node_js
      node_js: 12
      cache:
        directories:
          - node_modules
      addons:
        sonarcloud:
          organization: "the-sciences-and-engineering-squad" # the key of the org you chose at step #3
          token: "1240cnTmnYmmDscEwAORM7uG885eyIZYNFTr7BNHq7HR/UZUbJJ4JTE13s94sgugiBlOXrl4falICALet2x/DYfaS3XHxnXPjUyXf+ktRUY/twOU0+zulhahIWUZitynonMsTMIGLm3bTQEeJHOhumE4UhQZTWcdM1XdODsBtuetuGcYjlTtea4Ak71dixkcYShM/4/E9rf4fj3Yney6sLHhEIATjFuBCITUWu9/1ttG7Q/Y+qxmZ+HOG6N/EusOZXHISN6ymPWYEssIG5wOXBr/TozdNMOHPlusJr740gn7X1OFUosd2jinupIu3I1Y/z3Oldkp4xUIzrURsEuUCwFuSqyjCuB8/ghMUJ+Nb3Oradok1J74HsxSAw4INUeSdU'zDRODDLBcOL062Zs2hf7WiDR7ApiiEi9lusuzHbEljr0d1TihuSsSuzLIeYxCYqpQ7B9ULe+XINRoIs-FRDfAxXN6UXU8XcwoBx41,17xnTdRI7u0Fx2AkAAryQHzIuggluniCUFHugSx8A0M5BQXo6uiwb+ZpEillIqFZWI+BGM3P5cHilMo08j9XPbMqJjCNsiAzIoWhigulPpucqq5XrfSrJ2gFrGsueDial308.00-GHnMoN0UhLrpPEsDpAtiodQ0NOOxIiidkkjqZ1CzsPL7R9ZOYHWu2FRXDYQ3s="
      before_install:
        - cd client
      install:
        - npm install
      script:
        - npm test
        - npm run test:coverage
        - npm run build
        # other script steps might be done before running the actual analysis
        - sonar-scanner
    - language: python
      env:
        - FLASK_APP=server
        - FLASK_ENV=development
      addons:
        sonarcloud:
          organization: "the-sciences-and-engineering-squad" # the key of the org you chose at step #3
          token: "1240cnTmnYmmDscEwAORM7uG885eyIZYNFTr7BNHq7HR/UZUbJJ4JTE13s94sgugiBlOXrl4falICALet2x/DYfaS3XHxnXPjUyXf+ktRUY/twOU0+zulhahIWUZitynonMsTMIGLm3bTQEeJHOhumE4UhQZTWcdM1XdODsBtuetuGcYjlTtea4Ak71dixkcYShM/4/E9rf4fj3Yney6sLHhEIATjFuBCITUWu9/1ttG7Q/Y+qxmZ+HOG6N/EusOZXHISN6ymPWYEssIG5wOXBr/TozdNMOHPlusJr740gn7X1OFUosd2jinupIu3I1Y/z3Oldkp4xUIzrURsEuUCwFuSqyjCuB8/ghMUJ+Nb3Oradok1J74HsxSAw4INUeSdU'zDRODDLBcOL062Zs2hf7WiDR7ApiiEi9lusuzHbEljr0d1TihuSsSuzLIeYxCYqpQ7B9ULe+XINRoIs-FRDfAxXN6UXU8XcwoBx41,17xnTdRI7u0Fx2AkAAryQHzIuggluniCUFHugSx8A0M5BQXo6uiwb+ZpEillIqFZWI+BGM3P5cHilMo08j9XPbMqJjCNsiAzIoWhigulPpucqq5XrfSrJ2gFrGsueDial308.00-GHnMoN0UhLrpPEsDpAtiodQ0NOOxIiidkkjqZ1CzsPL7R9ZOYHWu2FRXDYQ3s="
      before_install:
        - cd server
      install:
        - pip install -r requirements.txt
      script:
        - python3 __init__.py
        - sonar-scanner